### PR TITLE
Upgrade to 0.13.55

### PR DESCRIPTION
**Pull request by shayne-fletcher**
Upgrade to SDK 0.13.55.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
`README.md` updates and upgraded react to be compatible with the daml2ts packages. May I suggest when you pull this branch:
```
git clean -xdf
yarn cache clean
yarn install
yarn workspaces run build
```

**Comment by shayne-fletcher** [comment]
@dimitri-da @gaborh-da i believe this is now good to go

**Comment by dimitri-da** [comment]
I'm giving it a quick spin and will approve soon

**Comment by shayne-fletcher** [comment]
Have upgraded react-scripts to 3.4. UI now loads.

**Comment by shayne-fletcher** [comment]
@georg-da Has kindly agreed to jump in on this fix it and convert it to TypeScript! 🥇

**Comment by GeorgSchneider** [comment]
This should work now, ok to merge @dimitri-da or you want to test again?

**Pull request merged**
